### ISSUE TITLE
 Compatibility of Yandex Ads

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#106]
Reference:  https://wordpress.org/support/topic/yandex-ads-in-plugin/

**Comment by wpquads** [comment]
escaping required: https://github.com/wpquads/quick-adsense-reloaded/commit/9388a5608d61d62a1912e3d88f4af5b6f039660f#diff-a85f6977f324b69743a9a59fd0887dbeR605

**Comment by jasthilokesh** [comment]
Fixed in the update 2.0.4
