### ISSUE TITLE
 Notice: Undefined index: enabled_on_amp in /customers/a/4/1/ravimagazine.com/httpd.www/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 929

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#108]
Fatal error on user's site: 
Notice: Undefined index: enabled_on_amp in /customers/a/4/1/ravimagazine.com/httpd.www/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 929
ref: https://secure.helpscout.net/conversation/1167119023/130205?folderId=3602639

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.3
