### ISSUE TITLE
To add a new option for WPQUADS where we just 1 ad and it replicates itself after certain paragraphs.

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#118]
There could be a method where we just insert 1 ad tag, and it auto replicates itself every 4 paragraphs. Then we do not need a middle ad or so. Automatically we know that after every 4-5 paragraphs, 1 ad is appearing. This is the most ideal template most users follow.

Reference: https://secure.helpscout.net/conversation/1173917248/131594?folderId=3602639
Reference: https://secure.helpscout.net/conversation/1173144929/131453?folderId=3602639

**Comment by jasthilokesh** [comment]
Added with the update 2.0.7
