### ISSUE TITLE
when wpquads plugin is activated, in amp on blog page only sigle post is geetting repeated

### ISSUE THREAD

**Issue by TMsravan** [wpquads/quick-adsense-reloaded#123]
Please see this video it is clearly shown: https://monosnap.com/file/Rnvzu7KZPvgWajazuQwAEDqjaEhx1U

https://secure.helpscout.net/conversation/1172421233/131290?folderId=1060556

https://celebshistory.com/amp/

**Comment by alexisekrygin** [comment]
I am the owner of the site! https://celebshistory.com
I updated the plugins WP Quads and the problem was solved)))
Thank Ahmedkalud and the AMPforWP team for your help! i

**Comment by jasthilokesh** [comment]
Issue fixed under the update 2.0.6
