### ISSUE TITLE
an http link is breaking the Secure protocol 

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#126]
REF: https://secure.helpscout.net/conversation/1174922987/131881?folderId=3602639

![2020-05-25_06-32-44](https://user-images.githubusercontent.com/16532359/83114145-3af0c000-a0e6-11ea-92aa-3d335b293eb8.png)

**Comment by jasthilokesh** [comment]
Issue fixed under the update 2.0.6
