### ISSUE TITLE
CSS showing in the head of the website in AMP after update

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#165]
https://www.verhaal.ng/Blog/5-types-of-blog-to-use-for-your-business/types-of-blog/
https://mindfly.blog/
https://www.cambiarevita.eu/?amp
https://secure.helpscout.net/conversation/1181831823/133224/

**Comment by wpquads** [comment]
Ready to go.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.8
