### ISSUE TITLE
Notice: Undefined variable: posts_data in /customers/f/8/4/journalista.dk/httpd.www/wp-content/plugins/quick-adsense-reloaded/admin/includes/rest-api-service.php on line 365

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#177]
User sees this notice:
Notice: Undefined variable: posts_data in /customers/f/8/4/journalista.dk/httpd.www/wp-content/plugins/quick-adsense-reloaded/admin/includes/rest-api-service.php on line 365

website: https://journalista.dk/
ref: https://secure.helpscout.net/conversation/1192845940/135571?folderId=3602653

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.8
