### ISSUE TITLE
debug error

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#179]
When I hit a 404 page on my website it shows this error. I deactivated the plugin for now, but love to keep using it.

Notice: Trying to get property ‘ID’ of non-object in /var/www/nlgeldlenen-nuea/wordpress/current/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php on line 587.

It shows this notification 12 times on a 404 page.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.8.1
