### ISSUE TITLE
Need to create an option to remove "<! - WP QUADS - Quick AdSense Reloaded v.2.0.7 Content AdSense async ->" for pro users

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#180]
Need to create an option to remove "<! - WP QUADS - Quick AdSense Reloaded v.2.0.7 Content AdSense async ->" for pro users
ref: https://secure.helpscout.net/conversation/1175205363/131935?folderId=3602653

**Comment by akashagrjsr** [comment]
https://secure.helpscout.net/conversation/1441082628/183219?folderId=2770545
one more user wants to hide the ids of the ads in the source code.

**Comment by jasthilokesh** [comment]
Fixed with update 2.0.21
