### ISSUE TITLE
Issue in Random ads selection

### ISSUE THREAD

**Issue by MohammedKaludi** [wpquads/quick-adsense-reloaded#197]
If an ad is already selected then it should be removed from the dropdown, because of this same ad can be selected multiple times.

![image](https://user-images.githubusercontent.com/16618009/86024158-42d7b300-ba4a-11ea-9032-33243dfdbb06.png)

https://monosnap.com/file/Ca81SXucTm4wwDXgRfpryCsB5myRoL

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.9.1
