### ISSUE TITLE
Delete Data on Uninstall option in tools is not working for the new interface and for old interface data is getting deleted

### ISSUE THREAD

**Issue by TMsravan** [wpquads/quick-adsense-reloaded#207]
Delete Data on Uninstall option is not working even though the option is enabled and then we uninstall the plugin and activate it again the old data is still present in the new interface.

see this video the issue is shown: https://monosnap.com/file/lq1AEtKxffVYRQw8FWUuRz2mScSllm

Ref: https://secure.helpscout.net/conversation/1223968484/141702?folderId=2632030

2. Old setting issue ref link: https://monosnap.com/file/4NbabuQRSXVd0t2inNYjCfBgD87QPW

once after deleting the old data and by default setting show ad post type equals to post is shown as selected, but the ad is not displaying on the post. and once we reselect the option post type the ads are displaying.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.10
