### ISSUE TITLE
New Conditional ad by wordcount

### ISSUE THREAD

**Issue by rene-hermenau** [wpquads/quick-adsense-reloaded#23]
Would it be possible to ad a new feature called Word count? So the position of the ad is based on word count or characters? Just like "Paragraph". So a new feature under Generel Settings --> Position - automatic.
Example: 
Assign "ad1"  After Word Count "50" →  to End of Post if fewer Words are found.

**Comment by wpquads** [comment]
Ready to go.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.8
