### ISSUE TITLE
The width and height of the AdSense Ads through the shortcode

### ISSUE THREAD

**Issue by akashagrjsr** [wpquads/quick-adsense-reloaded#237]
Ref: https://secure.helpscout.net/conversation/1244960370/146521?folderId=2770545

If the user is adding the Ads of the 300*600 of Adsense through the shortcode then the Ads are not loading with proper width and height.

Screenshot: https://prnt.sc/u4r2cd

The issue is also recreating on the local as well.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.12
