### ISSUE TITLE
Visibility condition not working in Image banner Ad

### ISSUE THREAD

**Issue by JNAzeem** [wpquads/quick-adsense-reloaded#242]
In Image banner Ads Visibility condition not working when 'Where Will The AD Appear?' is set to "below the header". Issue is occurring in localhost also. 
screenshot: https://monosnap.com/file/znII1qIovYBuB7156rU572Xr4jIHxE
ref: https://secure.helpscout.net/conversation/1262387841/150129?folderId=3953286

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.12
