### ISSUE TITLE
Unable to modify ads size on moblie view.

### ISSUE THREAD

**Issue by amer07** [wpquads/quick-adsense-reloaded#248]
Case 1:https://secure.helpscout.net/conversation/1269659109/151589?folderId=2770543

The user chooses 320*100 this size for the mobile version, it does not show the effect on the mobile view.

Screenshot:https://prnt.sc/uau8qv
https://prnt.sc/uaua4m

**Comment by jasthilokesh** [comment]
Duplicate ticket 

Ref: https://github.com/wpquads/quick-adsense-reloaded/issues/256
