### ISSUE TITLE
Hide ads not working for in content ads

### ISSUE THREAD

**Issue by nakib4tech** [wpquads/quick-adsense-reloaded#249]
Hi, When I mark “Hide all ads on page” from the gutenberg editor, in-content ads like ad after 3rd paragraph or ad after 20% are still show up.
Here is a [Post](https://nakib4tech.com/%d8%a5%d9%86%d8%b4%d8%a7%d8%a1-%d9%85%d9%88%d9%82%d8%b9-%d9%88%d9%88%d8%b1%d8%af%d8%a8%d8%b1%d9%8a%d8%b3-%d9%85%d8%ac%d8%a7%d9%86%d8%a7%d9%8b/)  that i'd marked "hide all ads on page" check mark for it but some ads are still showing.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.13
