### ISSUE TITLE
Need to create an option to load ads in the auto next posts.

### ISSUE THREAD

**Issue by laharikakuna** [wpquads/quick-adsense-reloaded#255]
In the Bimder theme, we have an option called "Autoload next post"(https://prnt.sc/ugzilw). By using this option In a single post we can display the next posts. So need to create an option to load the ad in the next post also.

Ref video:https://monosnap.com/file/AvNVPXc22WWNJeVpGjkmRsy5V98E4r

Ref: https://secure.helpscout.net/conversation/1277504722/153446?folderId=3575684

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.14
