### ISSUE TITLE
When the "Ad block plus " enabled the New interface option panel is displaying  a blank page.

### ISSUE THREAD

**Issue by laharikakuna** [wpquads/quick-adsense-reloaded#258]
When the "Ad-block plus " enabled the New interface options panel is displaying a blank page(https://prnt.sc/uiq0vz) and also it displaying an error message when we the open any post/page as per the screenshot(https://prnt.sc/uipwv5).

Ref:https://secure.helpscout.net/conversation/1280184840/153896?folderId=3575684.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.15
