### ISSUE TITLE
Cache management 

### ISSUE THREAD

**Issue by vendeesign** [wpquads/quick-adsense-reloaded#262]
Hello, 

We're experiencing problems in the version 2.0.13 with cache management and cache loading (tested with WP Super Cache and WP Rocket).

For example : When we ban the ad in DESKTOP and the first user generating the cache comes in MOBILE (ads are authorized in MOBILE), the page is loaded with the ads for everyone using the site with cache. There was no problem when ads were called with .document.write (tested with 2.0.3 of Quads)

Thank you

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.15
