### ISSUE TITLE
Need to add the support of "Sticky floating"ads.

### ISSUE THREAD

**Issue by laharikakuna** [wpquads/quick-adsense-reloaded#263]
Need to add the support of "Sticky floating" ads.

Ref:https://secure.helpscout.net/conversation/1299505594/157302?folderId=3575684

**Comment by akashagrjsr** [comment]
one more user requested for it.
Ref: https://secure.helpscout.net/conversation/1427813999/181152/

**Comment by jasthilokesh** [comment]
one more user requested for it.
Ref:https://secure.helpscout.net/conversation/1429743092/181516?folderId=4405906

**Comment by jasthilokesh** [comment]
one more user requested for it.
Ref:https://secure.helpscout.net/conversation/1449773946/185097?folderId=4459751

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.23
