### ISSUE TITLE
bbPress support

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#264]
1 – adding an advertisement under the first pstem on the forum
2 – adding an advertisement at the bottom of the forum post
Hello, it’s nice if the plug could also be added to bbpress, which is the most popular forum on wordpress. For example, under 1 post or in the middle of topics – some forum support.

https://wordpress.org/support/topic/bbpress-forum-support/#post-13456595

**Comment by jasthilokesh** [comment]
FIxed the update 2.0.17
