### ISSUE TITLE
Cache Management 2.0.15

### ISSUE THREAD

**Issue by vendeesign** [wpquads/quick-adsense-reloaded#265]
Hello,

In continuation with the issue #262

I just tested with the 2.0.15 version (WP Rocket)and there's still a problem.

When you do the test, you have to make it in private browsing. If you're connected, you can't see the problem, as the cache is disabled by default for connected users.

The test process should be : 
- Creating a new ad, with an interdiction to display it on Desktop
- Emptying the caches 
- Loading a website page on your mobile --> the ad loads correctly
- Loading the same page in private (disconnected of wordpress) -> ad loads too, while it shouldn't

Merci

**Comment by jasthilokesh** [comment]
Ref: https://github.com/wpquads/quick-adsense-reloaded/issues/269

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.16
