### ISSUE TITLE
Need to add an option to remove/hide Ads Tag in editor text box

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#267]
Screenshot: https://www.lavocedivenezia.it/wp-content/uploads/xwpquads.jpg
Reference: https://wordpress.org/support/topic/ads-tag-in-editor-text-box/

**Comment by jasthilokesh** [comment]
We already had this option under the Legacy tag in the new interface 
![image](https://user-images.githubusercontent.com/9262187/98896314-b09eeb80-24ce-11eb-8b1e-5fb08e5737c2.png)
