### ISSUE TITLE
While  trying to export ads settings it shows 401 status

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#271]
While  trying to export ads settings it shows :  {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}

Reference: https://secure.helpscout.net/conversation/1327326332/162894
screenshot: https://prnt.sc/vce808

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.20
