### ISSUE TITLE
Need to add the Ads rotator feature

### ISSUE THREAD

**Issue by akashagrjsr** [wpquads/quick-adsense-reloaded#274]
Ref: https://secure.helpscout.net/conversation/1325854336/162642?folderId=2770545

We need to add the ads rotator feature in our plugin. We need to add the below features inside it.

- Repeat ads on paragraphs

- Limit on how many till paragraph it should display

- Do not insert on for a first nth paragraph

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.18
