### ISSUE TITLE
PHP Deprecated:  implode()

### ISSUE THREAD

**Issue by thomasarie** [wpquads/quick-adsense-reloaded#277]
It seems that the code is not fully compatible with PHP 7.4.

I got the warning: PHP message: PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /home/myhome/directory/wordpress/wp-content/plugins/quick-adsense-reloaded/includes/vendor/vi/render.php on line 147" while reading response header from upstream.

Environment: Ubuntu 20.04, nginx, PHP 7.4.3

**Comment by jasthilokesh** [comment]
Fixed with update 2.0.21
