### ISSUE TITLE
Random Ads option does not work. 

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#278]
Random Ads option does not work when trying to display the ad using the shortcode. 
Tested on the localhost, and the issue re-occurred. 

**The ads that were chosen in the random ads were "banner ads".** 

Ref: https://secure.helpscout.net/conversation/1313787296/160210?folderId=3514643

**Comment by JNAzeem** [comment]
Targeting condition not working while using shortcode.
Ref: https://wordpress.org/support/topic/device-type-condition-not-working/

**Comment by TMsravan** [comment]
Random Ads not displaying while using a shortcode.

https://secure.helpscout.net/conversation/1384634353/173266?folderId=2632030

**Comment by jasthilokesh** [comment]
Fixed the update 2.0.19.
