### ISSUE TITLE
Theme ad location

### ISSUE THREAD

**Issue by vdwijngaert** [wpquads/quick-adsense-reloaded#284]
Hey! Just checking; it appears as though custom ad location (by means of `quads_register_ad`) do not work yet in the new react-based version of this plugin. Is that correct? 

In case I was correct; 

* is this going to be included again somewhere in the future? 
* is it okay to keep using the old interface, or will this eventually break too?

Thanks!

**Comment by jasthilokesh** [comment]
Fixed with update 2.0.21
