### ISSUE TITLE
Exclude targeting is not working.

### ISSUE THREAD

**Issue by laharikakuna** [wpquads/quick-adsense-reloaded#286]
Exclude targeting is not working when the logged In -True.

Ref screenshot1:  https://prnt.sc/vrpzbz
Ref screenshot2:  https://prnt.sc/vrpzx0

Ref: https://secure.helpscout.net/conversation/1347257773/166613?folderId=3575684

**Comment by jasthilokesh** [comment]
Fixed the update 2.0.19.
