### ISSUE TITLE
Google Auto Ads script is not getting saved

### ISSUE THREAD

**Issue by TMsravan** [wpquads/quick-adsense-reloaded#293]
Google Auto Ads script is not getting saved, The option auto ads enabled is not getting saved even though it is saved. 

https://secure.helpscout.net/conversation/1384634353/173266?folderId=2632030

- Google adsense autoads -> script is NOT saved and auto disabled after saving settings.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.18.1

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.18.1
