### ISSUE TITLE
Need to avoid getting Ads displayed on 404 error pages

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [wpquads/quick-adsense-reloaded#301]
The user is requesting an option to exclude Ads on 404 pages. 
Reference ticket: https://secure.helpscout.net/conversation/1400190954/176253?folderId=4074390
Reference web page: http://thehandmadecrafts.com/2019/09/most-beautiful-sleeve-designs/

**Comment by jasthilokesh** [comment]
![image](https://user-images.githubusercontent.com/9262187/108359402-f7128d80-7215-11eb-83b6-7e13b4a0a6c4.png)

issue was happing because of other plugin.

**Comment by jasthilokesh** [comment]
Issue was not with the Quads

The ad code was integrated manually with the theme.
