### ISSUE TITLE
Manual Ads not displaying

### ISSUE THREAD

**Issue by JNAzeem** [wpquads/quick-adsense-reloaded#304]
Unable to re-create the issue at local.
WordPress ref: https://wordpress.org/support/topic/last-update-manually-inserted-ads-not-displaying/
https://wordpress.org/support/topic/old-version-19/

**Comment by kerdezo** [comment]
This is my system data, (to recreate the issue)
# SITE_URL:               https://www.mosthallottam.hu
# HOME_URL:               https://www.mosthallottam.hu
# IS MULTISITE :          No

# ACTIVE THEME :          Hueman Child 1.0.0
# PARENT THEME :          Hueman 3.7.1
# WP VERSION :            5.6
# PERMALINK STRUCTURE :   /%category%/%postname%/
# 10 ACTIVE PLUGINS :
                          - AdSense Integration WP QUADS (version 2.0.17.1)
                          - Akismet Anti-Spam (version 4.1.8)
                          - EU Cookie Law (version 3.1.6)
                          - Exit Popup (version 3.1)
                          - Google Analytics Dashboard for WP (GADWP) (version 5.3.9)
                          - Hueman Addons (version 2.3.0)
                          - Limit Login Attempts (version 1.7.1)
                          - Super Socializer (version 7.13.11)
                          - WP-PageNavi (version 2.93.3)
                          - Yoast SEO (version 10.1.3)

# PHP Version:            7.4.13
# MySQL Version:          10.3.27-MariaDB-cll-lve
# Web Server Info:        Apache

# WordPress Memory Limit: 40MB
# PHP Memory Limit:       256M
# PHP Upload Max Size:    30M
# PHP Post Max Size:      20M
# PHP Upload Max Filesize:30M
# PHP Time Limit:         300
# PHP Max Input Vars:     1000
# PHP Arg Separator:      &
# PHP Allow URL File Open:Yes
# WP_DEBUG:               Disabled

# Show On Front:          posts
# Page On Front:          (#0)
# Page For Posts:         (#0)

**Comment by kerdezo** [comment]
Updating to 2.0.19. solved the problem. Now all ads are visible, both manually inserted and automated ones:
