### ISSUE TITLE
"Lazy loading for Adsense" toggle is not working properly if lite speed cache plugin is activated.

### ISSUE THREAD

**Issue by kunalaharika** [wpquads/quick-adsense-reloaded#310]
"Lazy loading for Adsense" toggle is not working properly if the lite speed cache plugin is activated

Ref:https://secure.helpscout.net/conversation/1406645489/177251?folderId=3575684

ref video of local host: https://monosnap.com/direct/hzeNAbLCGe1Ja5ARZ2vN2aAQuCnQSs

**Comment by jasthilokesh** [comment]
![image](https://user-images.githubusercontent.com/9262187/108359799-72743f00-7216-11eb-9dc4-b76c3981ef7a.png)

Issue was happing because of other plugin.
