### ISSUE TITLE
WP quads ads block is not working properly in the widgets section.

### ISSUE THREAD

**Issue by kunalaharika** [wpquads/quick-adsense-reloaded#314]
WP quads ads block is not working properly in the widgets section.

Even after deleting the ad. The ad is still displayed in the wp quads ads block of the widget.

Ref video: https://monosnap.com/direct/xLkVlQZWT1hh8JddsZkW6kcsYoCbBF

Ref: https://secure.helpscout.net/conversation/1406645489/177251?folderId=3575684

**Comment by jasthilokesh** [comment]
Fixed with update 2.0.21
