### ISSUE TITLE
Shortcode does not work on HP page and topic.

### ISSUE THREAD

**Issue by vendeesign** [wpquads/quick-adsense-reloaded#315]
Hello Team,

- AdSense Integration WP QUADS 2.0.19
- AdSense Integration WP QUADS PRO 2.0.3

When selecting in "Targeting" Shortcode, the "Visibility" filters no longer appear and the default setting seems to be "Post" only. Suddenly the advertisements do not load on the HP and on the sections, when Shortcode is active.

Thanks

Benjamin

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.20
