### ISSUE TITLE
Custom post type does not work

### ISSUE THREAD

**Issue by vendeesign** [wpquads/quick-adsense-reloaded#319]
Hello Team,

- AdSense Integration WP QUADS 2.0.20.1
- AdSense Integration WP QUADS PRO 2.0.3

In the "Visibility" tab, adding custom post type does not work.
Also be careful, when in the "Position" tab shortcode is selected, it does not work either. No ads charge.

Thanks

**Comment by jasthilokesh** [comment]
Ref: https://github.com/wpquads/quick-adsense-reloaded/issues/321
