### ISSUE TITLE
In Random ads Exclude targeting is not working well when the exclude by any specific page 

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#320]
A user is facing an issue with exclude targeting in Random ads:

Screenshot: https://prnt.sc/100hgvp
Website: https://estacaodomarketing.com.br/
Reference: https://secure.helpscout.net/conversation/1429128704/181405

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.22
