### ISSUE TITLE
The visibility conditions for the ads are not working properly for some users

### ISSUE THREAD

**Issue by akashagrjsr** [wpquads/quick-adsense-reloaded#325]
Ref: https://secure.helpscout.net/conversation/1441082628/183219?folderId=2770545

Screenshot: https://prnt.sc/10htxja

When we are testing the changing the IP of the other country like Germany and UK then also the ads are showing in the postman.
Screenshot: https://prnt.sc/10hu2ya

So, we need to improve it and give proper AND and OR conditions.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.23
