### ISSUE TITLE
Click Fraud Protection is not working perfectly

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#332]
The user sets a limit to the ad click, but it was able to click more than the limit. The ads never blocked. 

Screenshot: https://prnt.sc/10s91o0
https://prnt.sc/10s91xr
website URL: https://sendcv.co.za/2021/03/17/south-african-national-parks-sanparksinternship-programme/
Reference: https://secure.helpscout.net/conversation/1457405872/186749/

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.24
