### ISSUE TITLE
No country names when selected Country from the Excluded list.

### ISSUE THREAD

**Issue by Arihantkankariya09** [wpquads/quick-adsense-reloaded#336]
https://prnt.sc/111em5u

https://secure.helpscout.net/conversation/1466542718/188085?folderId=1060556

**Comment by jasthilokesh** [comment]
This issue was user-specific only happen for the users who are using the Cloudflare server 

Ref:https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs
it was fixed in the pro version update.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.24
