### ISSUE TITLE
Geolocation targeting feature is not working on the AMP.

### ISSUE THREAD

**Issue by Arihantkankariya09** [wpquads/quick-adsense-reloaded#337]
When the user selects included in-country, then the ads do not display on the AMP. By default, if blank the ads are shown.

https://secure.helpscout.net/conversation/1466542718/188085?folderId=1060556

**Comment by jasthilokesh** [comment]
This issue was user-specific only happen for the users who are using the Cloudflare server

Ref:https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs
it was fixed in the pro version update.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.24
