### ISSUE TITLE
Fixed Widget option is not working properly

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#342]
Reference Ticket URL: https://secure.helpscout.net/conversation/1477706460/190112/

Fixed widget option not working as expected with image banner.

**Comment by jasthilokesh** [comment]
Ref: https://github.com/wpquads/quick-adsense-reloaded/commit/b9551bac5a21f221310aa3e33d85f37f6bad31f8

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.27
