### ISSUE TITLE
Fatal error and warning (using php version 8)

### ISSUE THREAD

**Issue by TMsravan** [wpquads/quick-adsense-reloaded#348]
Warning: Undefined array key "ads" in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\admin\includes\migration-service.php on line 68

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\admin\includes\migration-service.php on line 68

Warning: Undefined array key "ads" in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\admin\includes\migration-service.php on line 139

Warning: foreach() argument must be of type array|object, null given in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\admin\includes\migration-service.php on line 139

Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, string given in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\includes\admin\settings\register-settings.php:1526 Stack trace: #0 C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\includes\gutenberg\src\init.php(39): quads_get_ads() #1 C:\xampp\htdocs\wp7\wp-includes\class-wp-hook.php(292): quads_block_assets('') #2 C:\xampp\htdocs\wp7\wp-includes\class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\wp7\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\wp7\wp-settings.php(560): do_action('init') #5 C:\xampp\htdocs\wp7\wp-config.php(90): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\wp7\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\wp7\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\wp7\wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...') #9 {main} thrown in C:\xampp\htdocs\wp7\wp-content\plugins\quick-adsense-reloaded\includes\admin\settings\register-settings.php on line 1526

![image](https://user-images.githubusercontent.com/46995400/114990388-134d4680-9eb6-11eb-8403-d9b159ed7fd0.png)

Issue occurring in local.

using Php 8 VERSION.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.25.3
