### ISSUE TITLE
WP QUADS PRO plugin is getting conflict with Soliloquy (am image slider plug-in)

### ISSUE THREAD

**Issue by TMsravan** [wpquads/quick-adsense-reloaded#349]
issue is: 

https://secure.helpscout.net/conversation/1458539797/186935?folderId=1060556

When we upload a new gallery, or when we update an existing gallery to Soliloquy, I get the error "the link you followed has expired". 

When I disable the WP QUADS PRO plug-in, it works fine.

Please see this video the issue is shown in it:

https://drive.google.com/file/d/1xARvHktaURa3WyE8A6Oil3GfefwfX_ej/view?usp=sharing

![image](https://user-images.githubusercontent.com/46995400/114993215-37f6ed80-9eb9-11eb-9c85-b9a1277ece3e.png)

WP QUADS PRO  Version 2.0.3 |

**Comment by jasthilokesh** [comment]
Fixed with the pro version update
