### ISSUE TITLE
HTML Code getting break when we are placing ads by word count

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#357]
Reference Ticket URL: https://secure.helpscout.net/conversation/1500828540/193796?folderId=4409869

When we are placing ads "by word count" then at some places HTML code getting break.

Reference Screenshot: https://monosnap.com/file/33f2vyuRwNghhst2fo9mNiPY440Mj4

**Comment by Rkroy** [comment]
Issue not recreatable, so closing the ticket.
