### ISSUE TITLE
Multiple ads are not displaying when user embeds twitter feed in the posts.

### ISSUE THREAD

**Issue by sardarui** [wpquads/quick-adsense-reloaded#377]
When a user embeds a Twitter feed in his posts then multiple ads are not displaying on his post.

Issue URLs:
https://resistthemainstream.org/progressive-nfl-fans-erupt-over-tim-tebows-likely-nfl-return-but-not-colin-kaepernick/
https://resistthemainstream.org/squad-members-launch-an-attack-on-israel-as-hamas-rockets-hit-city/

Ref Ticket: 
https://secure.helpscout.net/conversation/1504648046/194947?folderId=3126461

**Comment by Sanjeevsetu** [comment]
This issue seems has been solved or invalid so I am closing it
