### ISSUE TITLE
Need to add an option where other role(Contributer, Auther & Editor) scan also access to WPQuads plugin.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#388]
While the admin of a site has full rights to the WPQuads plugin(enable, disable, and edit...etc).
Need to add an option where the admin can allow other roles(https://monosnap.com/direct/rCVTSKn7NceHQtaFppIOigxpbyuchP) to access to WPQuads plugin.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.29
