### ISSUE TITLE
user2 unable to see the ad placed by the user1.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#389]
A user installs the WPQuads plugin for his website. (website handling by two persons)
After installing **user1** checked WPQuads dashboard there are no ads.
The same **user2** also checked WPQuads dashboard there are no ads.

After some time **user1** place an ad in the WPQuad dashboard, then **user2** login and checked the WPQuads dashboard to edit the placed ad, 

But **user2** unable to see the ad placed by the **user1**.

**Comment by akshaywali** [comment]
Unable to recreate the issue  as of version 2.0.67.  User 1 is able to access ads created by User 2 and vice versa.
So closing this ticket. if anyone faces this issue please  open a new ticket
