### ISSUE TITLE
 Newspaper theme conflicts with WpQuads

### ISSUE THREAD

**Issue by HaripriyaHari** [wpquads/quick-adsense-reloaded#395]
The “Column Text Block” in tag div composer of Newspaper theme, doesn’t work when WP Quads plugin is active. 
When quads plugin is active: https://ibb.co/tsdRQ3d
When quads plugin is not active: https://ibb.co/4mmX8ff
Video: https://vimeo.com/572548852
Reference: https://secure.helpscout.net/conversation/1563234162/205295?folderId=4195936

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.27.2

**Comment by wpquads** [comment]
https://secure.helpscout.net/conversation/1563234162/205295/

Jalandhar Bulletin, [02.08.21 16:31]
When I create 3rd ad, it doesn't work properly.

System repeate second ad.

Jalandhar Bulletin, [02.08.21 16:31]
Please see screenshot.

Jalandhar Bulletin, [02.08.21 16:32]
I want to create 3 or more ads after header.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.29
