### ISSUE TITLE
Need to hide the license key.

### ISSUE THREAD

**Issue by kunalaharika** [wpquads/quick-adsense-reloaded#397]
Need to hide the license key.

Also, if the user has subscribed to the pro version, the "BECOME A PRO" banner should not be shown.

Ref screenshot: https://prnt.sc/19yf30t

Ref:https://secure.helpscout.net/conversation/1562627899/205238?folderId=3575684

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.28
