### ISSUE TITLE
USER END ISSUE:Save button not visiable on WP-QUADS widget.

### ISSUE THREAD

**Issue by amer07** [wpquads/quick-adsense-reloaded#398]
Ref:https://secure.helpscout.net/conversation/1558271746/204770?folderId=2770543

The problem is about the widgets that I use (in the sidebars) for displaying ads.  can not actually exclude from caching the widgets because I don't have the save button option on the widgets.

Screenshot:https://imgbb.com/5krqzwm

**Comment by amer07** [comment]
Furthermore i got to find out that , in some pages (post type = page) the ads are being displayed and in some others pages they don't.
The reason for this is the following inline js



<div id="quads-ad1-place" class="quads-ll">

<script type="text/javascript" >

var quads_screen_width = document.body.clientWidth;

if ( quads_screen_width >= 1140 ) {document.write('<ins style="display:inline-block;width:728px;height:90px;" data-ad-client="pub-1055623946622792" data-ad-slot="4734233927" ><span>Loading...</span></ins></div>');

instant= new adsenseLoader( '#quads-ad1-place', {

onLoad: function( ad ){

if (ad.classList.contains("quads-ll")) {

ad.classList.remove("quads-ll");

}

}

});

}if ( quads_screen_width >= 1024 && quads_screen_width < 1140 ) {document.write('<ins style="display:inline-block;width:728px;height:90px;" data-ad-client="pub-1055623946622792" data-ad-slot="4734233927" ><span>Loading...</span></ins></div>');

instant= new adsenseLoader( '#quads-ad1-place', {

onLoad: function( ad ){

if (ad.classList.contains("quads-ll")) {

ad.classList.remove("quads-ll");

}

}

});

}if ( quads_screen_width >= 768 && quads_screen_width < 1024 ) {document.write('<ins style="display:block;" data-ad-client="pub-1055623946622792" data-ad-slot="4734233927" data-ad-format="auto"><span>Loading...</span></ins></div>');

instant= new adsenseLoader( '#quads-ad1-place', {

onLoad: function( ad ){

if (ad.classList.contains("quads-ll")) {

ad.classList.remove("quads-ll");

}

}

});

}if ( quads_screen_width < 768 ) {document.write('<ins style="display:inline-block;width:336px;height:280px;" data-ad-client="pub-1055623946622792" data-ad-slot="4734233927" ><span>Loading...</span></ins></div>');

instant= new adsenseLoader( '#quads-ad1-place', {

onLoad: function( ad ){

if (ad.classList.contains("quads-ll")) {

ad.classList.remove("quads-ll");

}

}

});

}

</script>




<script type="text/javascript" src="data:text/javascript;base64,dmFyIHF1YWRzX3NjcmVlbl93aWR0aD1kb2N1bWVudC5ib2R5LmNsaWVudFdpZHRoO2lmKHF1YWRzX3NjcmVlbl93aWR0aD49MTE0MCl7ZG9jdW1lbnQud3JpdGUoJzxpbnMgIHN0eWxlPSJkaXNwbGF5OmlubGluZS1ibG9jazt3aWR0aDo3MjhweDtoZWlnaHQ6OTBweDsiIGRhdGEtYWQtY2xpZW50PSJwdWItMTA1NTYyMzk0NjYyMjc5MiIgZGF0YS1hZC1zbG90PSI0NzM0MjMzOTI3IiA+PHNwYW4+TG9hZGluZy4uLjwvc3Bhbj48L2lucz48L2Rpdj4nKTtpbnN0YW50PW5ldyBhZHNlbnNlTG9hZGVyKCcjcXVhZHMtYWQxLXBsYWNlJyx7b25Mb2FkOmZ1bmN0aW9uKGFkKXtpZihhZC5jbGFzc0xpc3QuY29udGFpbnMoInF1YWRzLWxsIikpe2FkLmNsYXNzTGlzdC5yZW1vdmUoInF1YWRzLWxsIil9fX0pfWlmKHF1YWRzX3NjcmVlbl93aWR0aD49MTAyNCYmcXVhZHNfc2NyZWVuX3dpZHRoPDExNDApe2RvY3VtZW50LndyaXRlKCc8aW5zICBzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6NzI4cHg7aGVpZ2h0OjkwcHg7IiBkYXRhLWFkLWNsaWVudD0icHViLTEwNTU2MjM5NDY2MjI3OTIiIGRhdGEtYWQtc2xvdD0iNDczNDIzMzkyNyIgPjxzcGFuPkxvYWRpbmcuLi48L3NwYW4+PC9pbnM+PC9kaXY+Jyk7aW5zdGFudD1uZXcgYWRzZW5zZUxvYWRlcignI3F1YWRzLWFkMS1wbGFjZScse29uTG9hZDpmdW5jdGlvbihhZCl7aWYoYWQuY2xhc3NMaXN0LmNvbnRhaW5zKCJxdWFkcy1sbCIpKXthZC5jbGFzc0xpc3QucmVtb3ZlKCJxdWFkcy1sbCIpfX19KX1pZihxdWFkc19zY3JlZW5fd2lkdGg+PTc2OCYmcXVhZHNfc2NyZWVuX3dpZHRoPDEwMjQpe2RvY3VtZW50LndyaXRlKCc8aW5zICBzdHlsZT0iZGlzcGxheTpibG9jazsiIGRhdGEtYWQtY2xpZW50PSJwdWItMTA1NTYyMzk0NjYyMjc5MiIgZGF0YS1hZC1zbG90PSI0NzM0MjMzOTI3IiBkYXRhLWFkLWZvcm1hdD0iYXV0byI+PHNwYW4+TG9hZGluZy4uLjwvc3Bhbj48L2lucz48L2Rpdj4nKTtpbnN0YW50PW5ldyBhZHNlbnNlTG9hZGVyKCcjcXVhZHMtYWQxLXBsYWNlJyx7b25Mb2FkOmZ1bmN0aW9uKGFkKXtpZihhZC5jbGFzc0xpc3QuY29udGFpbnMoInF1YWRzLWxsIikpe2FkLmNsYXNzTGlzdC5yZW1vdmUoInF1YWRzLWxsIil9fX0pfWlmKHF1YWRzX3NjcmVlbl93aWR0aDw3Njgpe2RvY3VtZW50LndyaXRlKCc8aW5zICBzdHlsZT0iZGlzcGxheTppbmxpbmUtYmxvY2s7d2lkdGg6MzM2cHg7aGVpZ2h0OjI4MHB4OyIgZGF0YS1hZC1jbGllbnQ9InB1Yi0xMDU1NjIzOTQ2NjIyNzkyIiBkYXRhLWFkLXNsb3Q9IjQ3MzQyMzM5MjciID48c3Bhbj5Mb2FkaW5nLi4uPC9zcGFuPjwvaW5zPjwvZGl2PicpO2luc3RhbnQ9bmV3IGFkc2Vuc2VMb2FkZXIoJyNxdWFkcy1hZDEtcGxhY2UnLHtvbkxvYWQ6ZnVuY3Rpb24oYWQpe2lmKGFkLmNsYXNzTGlzdC5jb250YWlucygicXVhZHMtbGwiKSl7YWQuY2xhc3NMaXN0LnJlbW92ZSgicXVhZHMtbGwiKX19fSl9" defer>

with a defer attribute, and i just don't now why this is happening. I really don't know how can i remove the defer attribute from lightspeed cache plugin.

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.30

**Comment by merajali294** [comment]
not recurring
