### ISSUE TITLE
ads.txt Error With WP Quads

### ISSUE THREAD

**Issue by Shivam704** [wpquads/quick-adsense-reloaded#433]
User is using a ads.txt plugin but anything he is updating on WPQUADS it overrides his ads.txt plugin. please fix this as soon as possible.

Here is the link for more details.
https://wordpress.org/support/topic/ads-txt-error-with-wp-quads/

**Comment by Sanjeevsetu** [comment]
the issue is not being happened at my end. Just keep ads.txt creation option turn off, if you do not want ads.txt from this plugin.
