### ISSUE TITLE
Unable to link google adsense account for the Revenue Reports Feature

### ISSUE THREAD

**Issue by mohmmadasim** [wpquads/quick-adsense-reloaded#452]
Ticket reference -- https://secure.helpscout.net/conversation/1728657177/220125?folderId=5633920

The user has reported that he is unable to link the google Adsense account for the Revenue Reports Feature and while connecting to the account it gives an error message.

And also the tested this feature on the test site and it is giving the same error 

Attached a few screenshots for reference - https://prnt.sc/23ebjfc
                                                                     https://prnt.sc/23eo6z6

**Comment by merajali294** [comment]
Pushed in 2.0.39
