### ISSUE TITLE
If I activate the plugin, it mess up my registration page. 

### ISSUE THREAD

**Issue by Nwakamma** [wpquads/quick-adsense-reloaded#460]
If I activate the plugin, it mess up my registration page. Both Youzify and ultimate member (plugin) registration form.
It will be showing codes on the page.

**Comment by merajali294** [comment]
@Nwakamma , have tested this issue and it doesn't recur at our end. Please reach out us at support@magazine3.in and our team will co-ordinate & help you further in fixing this.
