### ISSUE TITLE
wpquads "Live ad rotation in one group as a grid"

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#461]
https://secure.helpscout.net/conversation/1753717263/222143?folderId=2498305
Take a look at the sidebar here: https://www.youtube.com/watch?v=V6JtxUhgMtE

Need to create this feature of Live ad rotation in one group as a grid for one of our customer.

**Comment by merajali294** [comment]
pushed in 2.0.40
