### ISSUE TITLE
Need to add a feature missing in Quads

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#468]
https://secure.helpscout.net/conversation/1778128197/226546?folderId=2498305
contact Ahmed sir for any assistance

**Comment by ahmedkaludi** [comment]
https://secure.helpscout.net/conversation/1778128197/226546?folderId=2498305
contact Ahmed sir for any assistance

**Comment by merajali294** [comment]
Pushed in 2.0.45
