### ISSUE TITLE
Shortcodes disappear in HTML view when "convert to blocks" old posts in Guttenberg

### ISSUE THREAD

**Issue by kerdezo** [wpquads/quick-adsense-reloaded#49]
Old posts created before Guttenberg contain the 'on-the fly' inserted ad codes in HTML view. (Like <!–Ads1–>,.... <!–RndAds–>)
After old posts 'Convert to blocks' in the Guttenberg editor the codes got invisible. (Though the codes must be there as they are still functioning.)
As the codes are invisible there is no way to change its' place or to erase.
Tested with:WP 5.3 and WP QUADS 1.8..8 , Theme:  Hueman (Best rated theme for blogs and magazines on WordPress.org. )

**Comment by jasthilokesh** [comment]
Ref: https://github.com/wpquads/quick-adsense-reloaded/issues/50
