### ISSUE TITLE
WPQUADS Showing PHP notices and warnings in the pluginstest.com

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#490]
Reference screenshot: https://prnt.sc/unR9Fp0UE-lT
Reference URL:  https://plugintests.com/plugins/wporg/quick-adsense-reloaded/latest
Reference ticket: https://wordpress.org/support/topic/php-warning-invalid-argument-supplied-for-foreach-46/

**Comment by merajali294** [comment]
Pushed in 2.0.45
