### ISSUE TITLE
impressions & clicks not counting properly

### ISSUE THREAD

**Issue by MohammedKaludi** [wpquads/quick-adsense-reloaded#515]

**Comment by merajali294** [comment]
Pushed in 2.0.49

**Comment by merajali294** [comment]
ref:-
https://github.com/wpquads/wp-quads-pro/commit/464636f9eaef1d9a7f3ebd3e20c860c4a52f6bcb#diff-ab8195d0d46d1d101c33f252f6e5335ae3d75a660043f2f0a493f657474f39e3
