### ISSUE TITLE
An option for display a "Ad" size as per the device 

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#521]
Scenario: 

Suppose If there is a ad, It should be display  the size of the Ad as per the device the user is using.
Person 1 that visits the page on a computer should be able to see the Billboard ADS.
Person 2 that visits the page on a tablet/ipad should be able to see the Netboard ADS.
Person 3 that visits the page on a mobile phone should be able to see Mobile ADS.`

Reference ticket: https://wordpress.org/support/topic/auto-insert-after-before-headings-h-tags/

**Comment by merajali294** [comment]
Pushed in 2.0.50
