### ISSUE TITLE
Sitka theme customiser breaking issue with WP Quads version 2.0.28

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#529]
Helpscout:-
https://secure.helpscout.net/conversation/1860568077/239321?folderId=5893563

Description:-
Customize section auto space added when a user activates the WP Quads plugin

Issue video.
https://monosnap.com/file/izEpbFK7kb1zQYBx5a58DLCU25Oil3

**Comment by ahmedkaludi** [comment]
assigned to Navin https://trello.com/c/s9jF7yFZ/13-sitka-theme-customiser-breaking-issue-with-wp-quads-version-2028-529-wpquads

**Comment by merajali294** [comment]
Pushed in 2.0.53
