### ISSUE TITLE
Option for insert "Ad Before HTML Tag" in the position "Where will the Ad appear" section

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#531]
Reference ticket: https://wordpress.org/support/topic/auto-insert-before-html-tags/

**Comment by kicheny** [comment]
Thanks for adding this feature suggestion/improvement. 

If possible, make it possible to add a **skip** number of "HTML Tags."

For example, I may apply auto-display ads After/Before HTML tags but I want **skip the first two tags** on an article. 

This can help avoid showing ADS After/Before HTML Tags that are available too early on an article/post.

**Comment by merajali294** [comment]
Pushed in 2.0.53
