### ISSUE TITLE
Three huge bugs when using custom position and image ads

### ISSUE THREAD

**Issue by frafor1988** [wpquads/quick-adsense-reloaded#553]
Hi there, there are two huge issues with this plugin which made me loose my day of work, so this is why I’m writing here.

First Issue: custom position cannot use “-“

I’ve defined several custom position for my theme in which I’m trying to show simple image banners.

I’ve followed this guide: https://wpquads.com/documentation/how-to-add-custom-ad-position-in-wp-quads/

However, it doesn’t seem to work.

I’ve checked the quads_ad() function in api.php and I’ve noticed it’s not possible to use hyphens when defining positions, because they’re exploded in an array that later won’t match the position name.

$api_pos = explode('-',$ads['position']);

So you should update the article (or the code somehow)

Second Issue: image banners are not recognized as such by quads_is_ad_image() in render-ad-function.php

After fixing the above by renaming all my positions, I’ve noticed that quads_render_ads() wasn’t rendering anything, unless banner are placed in pre-defined positions.

This happens because the quads_ad() function is used only to render custom positions (as you check $api_pos).

quads_render_ad() then checks the banner type via quads_is_ad_image().

However the checks within quads_is_ad_image() does not match the structure of $quads_options global variable.

if( isset($quads_options['ads'][$id]['ad_type']) && $quads_options['ads'][$id]['ad_type'] === 'ad_image') {
        return true;
    }

correct check should be:

if(isset($quads_options['ads']) && isset($quads_options['ads']['ads'])) {
      foreach($quads_options['ads']['ads'] as $key => $ad) {
        if($ad['ad_id'] == $id && $ad['ad_type'] == 'ad_image') {
          return true;
        }
      }
    }

However, still the image wasn’s showing, Why?

Because the quads_render_ad_image_async() function checks for $quad_options the same way quads_is_ad_image() did.

$image_render_src = $quads_options['ads'][$id]['image_src'];

There’s just no ID used as key in $quad_options. Fortunately, there’s the ‘quads_render_ad_image_async’ filter thus it’s easier to plug a temporary fix without editing the code, however the whole issue is huge!

Can you please fix ASAP?

**Comment by merajali294** [comment]
Pushed in 2.0.53
