### ISSUE TITLE
Ad blocker is showing pop-up even if the visitor's Ad blocker is disabled/unavailable

### ISSUE THREAD

**Issue by sajandara** [wpquads/quick-adsense-reloaded#556]
Ad blocker is showing pop-up/redirection/bar notification even if the visitor's Ad blocker is disabled/unavailable.

Ref ticket: https://magazine3.in/conversation/5011?folder_id=27

Ref screenshot: https://prnt.sc/WrycwCzbrRtt

**Comment by kicheny** [comment]
Thanks so much for acknowledging this issue. I do hope that development will be accelerated.

**Comment by merajali294** [comment]
pushed in 2.0.56

**Comment by kicheny** [comment]
Unfortunately, this issue is still there.
