### ISSUE TITLE
Need to fix "Ad blocker's pop-up is getting closed if the visitor is clicking anywhere on the screen"

### ISSUE THREAD

**Issue by sajandara** [wpquads/quick-adsense-reloaded#557]
A visitor should not be able to close the Ad blockers' pop-up until it clicks on the close button as the content of the website is getting accessible.

Ref ticket: https://magazine3.in/conversation/5011?folder_id=27

**Comment by kicheny** [comment]
Thanks so much for acknowledging this issue. I do hope that development will be accelerated.

**Comment by merajali294** [comment]
pushed in 2.0.55
