### ISSUE TITLE
 ADS not showing show if we are using a page scroll to ID

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#569]
Using Insert BEFORE HTML tags option  ADS not showing show if we are using a page scroll to ID

Reference plugin link: https://wordpress.org/plugins/page-scroll-to-id/

Reference ticket: https://wordpress.org/support/topic/bugs-auto-insert-before-html-tags/

**Comment by kicheny** [comment]
@ahmedkaludi this issue is related to issue 570. Kindly pull it to this milestone.

**Comment by merajali294** [comment]
pushed in 2.0.56
