### ISSUE TITLE
Using Auto Insert BEFORE HTML tags, It changes all text before the first HTML Tag on the page to the formatting of that tag

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#570]
Scenario: It changes all text before the first HTML Tag on the page to the formatting of that tag. For example, if the first HTML Tag is h2 on a page, and you have set the plugin to show ADS before H2 tags, any paragraphs/text before the first H2 tag on the page is converted to H2 as well.

Reference ticket: https://wordpress.org/support/topic/bugs-auto-insert-before-html-tags/

**Comment by merajali294** [comment]
pushed in 2.0.56
