### ISSUE TITLE
The ADS is not showing in before the HTML tag.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#576]
https://magazine3.in/conversation/11170?folder_id=29

The ADS is not showing in before the HTML tag.
ADS also shows in the last paragraph of an article even when there’s no HTML tag.
REF video: https://www.awesomescreenshot.com/video/9623886

**Comment by kicheny** [comment]
@ahmedkaludi kindly accelerate this issue.

**Comment by akshaywali** [comment]
fix pushed in update 2.0.60
