### ISSUE TITLE
Ad Performance Tracking is working independently even if the option is disabled.

### ISSUE THREAD

**Issue by sajandara** [wpquads/quick-adsense-reloaded#583]
Ad Performance Tracking is working independently even if the option is disabled.

Ref ticket: https://magazine3.in/conversation/11087?folder_id=4

**Comment by MohammedAkramU7** [comment]
Another user: https://magazine3.in/conversation/13289?folder_id=21

**Comment by merajali294** [comment]
pushed in 2.0.56
