### ISSUE TITLE
In classic interface If we add an AD by using short-code then getting a warning notice 

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#596]
Scenario: 

1. From 2.0.42 the warning appears.
2. By using the classic interface: https://prnt.sc/T9XK_kqUkc-M
Reference video: https://monosnap.com/direct/JztPB7B9I6hCgIKqc1BfN0OStvjncm
3. The warning notice appears when we give the shortcode, otherwise, it does not appear.

Reference ticket: https://wordpress.org/support/topic/an-error-statement-appears-at-the-top-of-the-article/

**Comment by akshaywali** [comment]
pushed in 2.0.57.1
