### ISSUE TITLE
quicktags not working

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#599]
https://garage3.magazine3.com/wp-admin/post.php?post=147909&action=edit

**Comment by akshaywali** [comment]
have to check issue on user case basis

**Comment by Sasirekhamarella** [comment]
https://wordpress.org/support/topic/shortcodes-and-quads-id1-have-been-removed-from-the-html-tab/

**Comment by akshaywali** [comment]
pushed in update 2.0.61
