### ISSUE TITLE
Need to fix the "quad_cc" parameter at the end of Post preview URLs.

### ISSUE THREAD

**Issue by ankit644** [wpquads/quick-adsense-reloaded#602]
After latest update (version 2.0.57.1) the plugin adds "quad_cc" parameter at the end of Post preview URLs.

Ref tickets:-

1.https://magazine3.in/conversation/32711?folder_id=21
2.https://magazine3.in/conversation/33032?folder_id=21
3.https://magazine3.in/conversation/32926?folder_id=21
4.https://magazine3.in/conversation/32999?folder_id=27
5.https://magazine3.in/conversation/32705?folder_id=27
6.https://magazine3.in/conversation/32839?folder_id=27
7.https://magazine3.in/conversation/32643?folder_id=15
8.https://magazine3.in/conversation/32966?folder_id=15
9.https://magazine3.in/conversation/14609?folder_id=15
10.https://magazine3.in/conversation/32974?folder_id=29
11.https://magazine3.in/conversation/32783?folder_id=4
12.https://magazine3.in/conversation/32698?folder_id=4
13.https://magazine3.in/conversation/32673?folder_id=39
14.https://magazine3.in/conversation/32993?folder_id=4

**Comment by akshaywali** [comment]
fixed in 2.0.58 update
