### ISSUE TITLE
Shortcode option is not working in elementor

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#608]
Freescout:- https://magazine3.in/conversation/28076?folder_id=21

Description:-
User adds the Google Adsense ads and uses the shortcode option, inserting the shortcode in elementor. Ads are not loading and there are errors in the console. 

Issue screenshot:-
https://monosnap.com/direct/xpvgAJ3AaB8rblBPlKLzZW54dkhLWO

**Comment by akshaywali** [comment]
This issue is because user is using Google AdSense code for production into staging . 
That is why he is getting 403 error from google. So issue is from user side . 
We have updated user about this , he has not responded . So we can close and mark as completed.

**Comment by akshaywali** [comment]
Since we got no reply from user we are marking this as completed
