### ISSUE TITLE
bugs while showing demo to a customer

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#625]
- [x] Loop ads not working: https://take.ms/Z68oQ
- [x] video ad should be clickable 
- [x] video ad should be size controlabble
- [x] Video ad should be autoplay  
- [x] Lightbox alignment issues: https://take.ms/6u6Iy
- [x] Lightbox mobile diff ads
- [x] group ads is confusing
- [x] A/B testing is confusing
- [x] hold on scroll is not working 
- [x]  Docs on all the ads on top

**Comment by akshaywali** [comment]
**For Loop Ads** 

1)if you want to show loop ads in all archive pages and blog then select then select visibility as

General - Show Globally

2) If you want to show loop ads on custom blog or custom archive page then select visibility as

Page -  Your custom page

3)If you want to show loop ads on some category then select visibility as

Post Category - Your Category Name

**Comment by akshaywali** [comment]
**Hold and scro** ads are working . Just to make it clear these ad works on mobile device only  in desktop they are like regular banner Ads

**Comment by akshaywali** [comment]
Ad list is loading now , basically API call was timed out just need to hard refresh , This happens when server is responding slow

![199209800-e334f859-30d6-45e5-b723-a9b7cb572dc9](https://user-images.githubusercontent.com/36995680/199210611-84a1c9f1-8a6f-4fcd-a9a6-90ac8412b778.png)

**Comment by akshaywali** [comment]
pushed in 2.0.63 update
