### ISSUE TITLE
Warning: Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#638]
![quads_error](https://user-images.githubusercontent.com/11539242/200823804-cdcae195-416a-457c-a813-4d440dfe87a0.png)

**Comment by Sanjeevsetu** [comment]
We have this issue in multiple jsx component.

**Comment by pradipshende** [comment]
pushed in the 2.0.65 update
