### ISSUE TITLE
Ads are not working in AMP and need some improvement 

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#644]
User placed
a) Carousel Ad via shortcode
b) Cube Ad
c) Video ad

There are not visible in AMP and slowing the AMP site.

A large number of requests are generating Reference Screenshot: https://prnt.sc/t_RqrnLrOUCO

Browser Console having many issues Reference Screenshot: https://prnt.sc/A-GbQz-JMTGq

**Comment by akshaywali** [comment]
pushed in update 2.0.67

**Comment by mohammed-qutubuddin** [comment]
Still, ads are not working in AMP
https://prnt.sc/x1l-05pa2wdE
