### ISSUE TITLE
There is an issue while adding the code for  the webplayer in Plan text, HTML, or JS, target the position as "sticky ads." 

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#645]
While adding the code for the webplayer in Plan text, HTML, or JS, target the position as "sticky ads." When we refresh the page, the ad area is grey for a few seconds before the webplayer appears. I've included the reference video below. 

Ref Video. https://monosnap.com/direct/HhBVUvgw5IdWBEGJkaRMPuWK4TDDfJ

Recreated Steps.
1. Create an ad
2. AD FORMAT Plan text/HTML/JS
3. Add the code 
4. Position sticky ads.
5. Then go to the page and reload the page.

Ref ticket. https://magazine3.in/conversation/72907?folder_id=29

**Comment by akshaywali** [comment]
pushed in update 2.0.66
