### ISSUE TITLE
Limit Amount Of Ads option is not working

### ISSUE THREAD

**Issue by 77naveenop** [wpquads/quick-adsense-reloaded#648]
If we are adding 3 ads and try to limit 2 ads, then this option doesn't works as it supposed to be.

Reference ticket -: https://magazine3.in/conversation/43855?folder_id=23

Reference Screenshot -: 
![Screenshot (1015)](https://user-images.githubusercontent.com/78167698/204242790-57afe7db-c18c-43dc-909f-7989f66c78d1.png)

**Comment by akshaywali** [comment]
pushed in update 2.0.67
