### ISSUE TITLE
Slow queries due to WP-Quads

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#652]
Before disabling wp-quads it's 9 sec: https://prnt.sc/HgFthLsyQcUX
after disabling wp-quads its 3 sec: https://prnt.sc/EA3SbtBE60wg
https://prnt.sc/2TTmtDzyPFNk

**Comment by pradipshende** [comment]
Resolved in #649

**Comment by akshaywali** [comment]
pushed in update 2.0.66
