### ISSUE TITLE
WPQuads is the heaviest plugin. It should be the lightest plugin.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#657]
It is the heavies plugin we have to make sure that it should have light queries.

Reference Screenshot: https://monosnap.com/file/OgWAP3q9sGsOX3RsLUWvFs0JOOQkhN
https://monosnap.com/file/SIrPrBAzLHDjCT96d7TH7FTIYSNv68

**Comment by pradipshende** [comment]
Resolved in #649

**Comment by akshaywali** [comment]
pushed in update 2.0.66
