### ISSUE TITLE
all the quads users who are using this ad format might face this issue,.

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#659]
<img width="1190" alt="PageSpeed Insights 2022-12-11 20-26-44" src="https://user-images.githubusercontent.com/16532359/206911239-825ad243-9305-4fa6-b24a-64f31f0591ac.png">

**Comment by pradipshende** [comment]
Issue resolved in #656 ticket, changes pushed in the 2.0.65 update
