### ISSUE TITLE
Need to optimize the queries of the plugin[User Specific Mukul]

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#660]
When WP-Quads are active and writers are working on the backend, at that time CPU usage is increasing and it leads to database connection loss issues.

The user using the below ad
1. Carousel ads in the header and sidebar
2. Video ad
3. Floating ad

a) There are many duplicate queries you can check in the query Monitor
https://prnt.sc/40r4_MwlKgZt

b) Slow queries, can check in the query Monitor

c) Slow queries from quads check on the server side
https://prnt.sc/IjN_dxUfVuy1
https://prnt.sc/qPsTy3lqzKvn
https://prnt.sc/2TTmtDzyPFNk

**Comment by Rkroy** [comment]
Need Discussion with Ahmed sir.
