### ISSUE TITLE
Function name must start with a proper prefix

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#669]
find the functions:

getTotalWidgets
getIPAddress
mashsb_hide_auto_ads_notice
remove_ads_for_wp_shortcodes
remove_ad_from_content
sanitize_post_meta
tcf_2_integration
wpquads_content_modifier
has_token

Inside quick-adsense-reloaded\includes\gutenberg\src\init.php there are many functions which have adsforwp as a prefix. its wrong.

**Comment by akshaywali** [comment]
pushed in update 2.0.67
