### ISSUE TITLE
Nonce missing inside ajax call handler 'quads_send_feedback'

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#670]

**Comment by Sanjeevsetu** [comment]
@ankit644 

From next time. Please reference ticket in commit. This, you have fixed but I can not see any commit here.

**Comment by akshaywali** [comment]
pushed in update 2.0.66

**Comment by MohammedAkramU7** [comment]
User need some modification https://magazine3.in/conversation/97312?folder_id=21

**Comment by akshaywali** [comment]
pushed in 2.0.68 update
