### ISSUE TITLE
Selection of custom from dropdown inside Log Tab throw console warning

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#677]
VM1648 react_devtools_backend.js:4012 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `f`. See https://fb.me/react-warning-keys for more information.
    in Fragment (created by f)
    in f (created by p)
    in div (created by p)
    in div (created by p)
    in p (created by Context.Consumer)
    in n (created by u)
    in n (created by u)
    in div (created by u)
    in div (created by u)
    in t (created by t)
    in t (created by u)
    in u

**Comment by akshaywali** [comment]
pushed in update 2.0.67
