### ISSUE TITLE
Fatal error on Ab testing ad (Pro)

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#682]
Fatal error: Cannot redeclare wpquads_content_pos_mid_modifier() (previously declared in D:\XAMPP\htdocs\magazine3\wp-content\plugins\wp-quads-pro\includes\template-functions.php:92) in D:\XAMPP\htdocs\magazine3\wp-content\plugins\wp-quads-pro\includes\template-functions.php on line 92

Ref: https://prnt.sc/kAxRvSpBbUNc

**Comment by akshaywali** [comment]
Code updated on PRO 2.0.18 - https://github.com/wpquads/wp-quads-pro/commit/320669ac38da0f31e7031569ba061c7d7b2722d9

**Comment by akshaywali** [comment]
pushed in WP Quads PRO 2.0.18
