### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#685]
Warning: Invalid argument supplied for foreach() in /home/customer/localhost/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1497

Warning: explode(): Empty delimiter in /home/customer/localhost/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1501

Warning: count(): Parameter must be an array or an object that implements Countable in /home/customerlocalhost/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1502

Warning: Invalid argument supplied for foreach() in /home/customer/localhost/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1505

Warning: implode(): Invalid arguments passed in /home/customer/localhost/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1523

Ref User: https://wordpress.org/support/topic/invalid-argument-error-20/

**Comment by akshaywali** [comment]
Similar Ticket  : https://github.com/wpquads/quick-adsense-reloaded/issues/698
