### ISSUE TITLE
Fatal error and gelocation not working

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#686]
Ref:- https://magazine3.in/conversation/78446?folder_id=21

Description:-
When the user activates the pro plugin 502 error is shown on the user's website.

Fatal error:-
[08-Dec-2022 05:55:25 UTC] PHP Fatal error: Uncaught Error: Cannot use object of type WP_Error as array in /home/demowebsites/123.demowebsites.club/wp-content/plugins/wp-quads-pro/includes/conditions.php:339
Stack trace:
#0 /home/demowebsites/123.demowebsites.club/wp-content/plugins/wp-quads-pro/includes/conditions.php(260): quads_get_ip_geolocation()
#1 /home/demowebsites/123.demowebsites.club/wp-includes/class-wp-hook.php(308): quadspro_visitor_comparison_logic_checker(false, Array)
#2 /home/demowebsites/123.demowebsites.club/wp-includes/plugin.php(205): WP_Hook->apply_filters(false, Array)
#3 /home/demowebsites/123.demowebsites.club/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php(637): apply_filters('quads_visitor_c...', false, Array)
#4 /home/demowebsites/123.demowebsites.club/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php(372): quads_visitor_comparison_logic_checker(Array)
#5 /home/demowebsites/123.demowebsites.club/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php(2732): quads_is_visito in /home/demowebsites/123.demowebsites.club/wp-content/plugins/wp-quads-pro/includes/conditions.php on line 339

**Comment by akshaywali** [comment]
Code Updated on  WP QUADS PRO 2.0.16

**Comment by akshaywali** [comment]
pushed in update WP QUADS PRO 2.0.16
