### ISSUE TITLE
Code Improvement as per WP guidlines

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#690]
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\admin\settings\register-settings.php. Line: 546, 777, 778, 797, 798, 823, 824, 826, 851, 852, 855, 881, 882, 885, 912, 913, 915, 916, 971, 996, 997, 1021, 1022,  Escaping is missing. check entire file. escaping is missing in almost everywhere.
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\admin\settings\register-settings.php. Line: 567 and 568. We must use a proper sanitization for it. like for email use email sanitization method.
- [x] When making database calls, it's highly important to protect your code from SQL injection vulnerabilities. You need to update your code to use wpdb calls and prepare() with your queries to protect them. eg check this function 'quadsGetPostIdByMetaKeyValue'. Please check entire plugin. Need help check our super related post plugin
- [x] After every new WP_Query. we should restore to orignal post. Check entire plugin. for help ( https://developer.wordpress.org/reference/classes/wp_query/ )
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\quick-adsense-reloaded\quick-adsense-reloaded.php. Line: 167 function update_data. plz check why we have commented update_option here. it makes this function useless.
- [x] Remove unused and commented code. check entire plugin
- [x] Remove extra new line in everyfile whereever it is. eg. https://prnt.sc/SpbelMpVt3o6
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\widgets.php. Check entire file. We have missed escaping at many places
- [x] D:\XAMPP\htdocs\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\render-ad-functions.php. Check entire file. We have missed escaping at many places

**Comment by akshaywali** [comment]
pushed in update 2.0.67
