### ISSUE TITLE
The Ad targeting option "Country" is not working properly.

### ISSUE THREAD

**Issue by sajandara** [wpquads/quick-adsense-reloaded#691]
Bug Name: The ad targeting option "Country" is not working properly.
Version Number: 2.0.66.2/ (Pro) 2.0.16
Reason: Bug
Issue reported by: User
Reference ticket: https://magazine3.in/conversation/88084?folder_id=27
Description: The targeting of the Ad is set to show in a specific country but it is shown globally.

**Comment by akshaywali** [comment]
Code Pushed on WP Quads Pro 1.7
