### ISSUE TITLE
Showing x sign on content upon the plugin activation

### ISSUE THREAD

**Issue by PrabhSingh7** [wpquads/quick-adsense-reloaded#693]
Upon the Activation of the plugin, the x sign from the Cube and Video ads start showing up in the Website content as per the below reference screenshot.  
https://prnt.sc/6TkSPaAHaauy

**Comment by akshaywali** [comment]
pushed in 2.0.68 update

**Comment by akshaywali** [comment]
x sign is still visible on pages the embed latest posts,
