### ISSUE TITLE
Deprecated error messages when activated the plugin

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#698]
Error log details: https://docs.google.com/document/d/1orJ0SC89QJYkTcDVVXTPE2aEeah46aHyzsfyTPFZkJY/edit
Reference screenshot: https://snipboard.io/QI3e5h.jpg
Reference ticket: https://wordpress.org/support/topic/critical-error-and-multiple-pages-dont-work/

**Comment by akshaywali** [comment]
pushed in update 2.0.67
