### ISSUE TITLE
Deprecated: Hook elementor/widgets/widgets_registered

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#703]
Error reference screenshot: https://prnt.sc/vGZSUNEzG8EU
error log: :` Deprecated: Hook elementor/widgets/widgets_registered is deprecated since version 3.5.0! Use elementor/widgets/register`

Reference ticket: https://wordpress.org/support/topic/deprecated-hook-elementor-widgets-widgets_registered/

**Comment by akshaywali** [comment]
pushed in 2.0.68 update
