### ISSUE TITLE
Undefined array key error

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#705]
Error log: 
`PHP Warning: Undefined array key in /home/admin/web/lovablevibes.co/public_html/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 1972
`
Reference ticket: https://wordpress.org/support/topic/php-8-0-compatibility-29/

**Comment by akshaywali** [comment]
pushed in 2.0.68 update
