### ISSUE TITLE
Google Adsense are not showing on the homepage.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#710]
When we add Google Adsense to the Homepage, it does not work; the ad area appears, but the ads do not appear. 

Ref screenshot:https://prnt.sc/T69DIoEesoSh 

Ref ticket: https://magazine3.in/conversation/102562?folder_id=29

**Comment by akshaywali** [comment]
Unable to  recreate this issue , Google Adsense  are  working fine. So closing this  ticket.
