### ISSUE TITLE
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in php 8.2

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#712]
Deprecated: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in D:\XAMPP\htdocs\magazine3\wp-content\plugins\wp-quads-pro\includes\admin\settings\advanced-settings.php on line 402

Ref: https://prnt.sc/H2siUM_6IDtv

**Comment by Rkroy** [comment]
Solution Provided in Pro Version.
