### ISSUE TITLE
To display Ads on the AMP version via JS script which is added through Elementor/other builders

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#72]
To display Ads on the AMP version via JS script which is added through Elementor/other builders

scenario: 
When a user wishes to add ads code via the HTML module in Elementor builder. It should display ads on the AMP version of the site too.

**Comment by jasthilokesh** [comment]
ref:
https://github.com/ampproject/amphtml/blob/master/ads/google/adsense.md

**Comment by jasthilokesh** [comment]
Fixed in with the update 1.8.15
