### ISSUE TITLE
There is a need to make a feature where users can add mobile device-specific ads.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#725]
There is a need to make a feature where users can add mobile device-specific ads.

We are currently manually adding mobile-specific ads by adding code, but we need to automate this process. 

This is code : Need to add this html code in the custom html AD formate

<div class="wpquads-desktop-ads">
// add desktop ad code
</div>

<div class="wpquads-mobile-ads">
// add mobile ad code
</div>

and add the css code in the custom css file or in customizer.

.wpquads-desktop-ads{ display:inherit;}
.wpquads-mobile-ads{ display:none;}

@media only screen and (max-width: 600px) {
.wpquads-desktop-ads{ display:none;}
.wpquads-mobile-ads{ display:inherit;}
}

**Comment by sajandara** [comment]
Another user requires the same functionality:
https://magazine3.in/conversation/112403?folder_id=27
