### ISSUE TITLE
      When we exclude the ads from the desktop but ads are still on the desktop,

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#726]
When we exclude the ads from the desktop but ads are still on the desktop,

Ref video: https://monosnap.com/direct/GSCUtCRMOoYHesQ7RHlA34LqNfKas5

Ref ticket: https://magazine3.in/conversation/111572?folder_id=29

**Comment by Rkroy** [comment]
Issue not recreatable, exclude function working fine at our end.
