### ISSUE TITLE
Need to make an option to show the pop up ad on bottom of the page/post

### ISSUE THREAD

**Issue by Sasirekhamarella** [wpquads/quick-adsense-reloaded#731]
Reference ticket: https://wordpress.org/support/topic/do-you-have-pop-up-ads-from-bottom-of-the-page/

**Comment by akshaywali** [comment]
![image](https://github.com/wpquads/quick-adsense-reloaded/assets/36995680/701f8198-9ab2-4ae4-a388-0083dc1b7cc3)


We have added option to so that popup sticks to top or bottom as selected by user


  Pushed in update 2.0.73

**Comment by essaund** [comment]
This feature was rushed, and the devs didn't even follow the instructions and demos I provided. Its integration is poor and works like a regular pop-up ad. 

I gave you the example of Bimber Theme, which you can use to compare notes. Not sure if the devs really spared some time to have a look at it. 

https://wordpress.org/support/topic/do-you-have-pop-up-ads-from-bottom-of-the-page/

**Comment by akshaywali** [comment]
@essaund 
Sorry for the utter inconvenience you have faced . Can you please share the video demo for the ad so that there is no more confusion left .

**Comment by essaund** [comment]
@akshaywali ~ Thanks for your reply. Here's the video
https://drive.google.com/file/d/1OEWkdir5qDhM1Ez_H5OmoCYczovGsdHW/view?usp=sharing

**Comment by akshaywali** [comment]
Reopening this ticket since the implementation was not done according to the requested feature .

**Comment by essaund** [comment]
Thank you so much. 💯💯💯

**Comment by Rkroy** [comment]
Hi @essaund, we have updated the code as requested, please find this feature inside **Sticky Ad** option of **Where Will The AD Appear?** section, let us know if this helps.
![image_2023-08-29_16-09-41](https://github.com/wpquads/quick-adsense-reloaded/assets/43204388/fafa927c-de89-495b-b9c7-0712a6277274)

**Comment by essaund** [comment]
@Rkroy thank you so much!!! Looking forward to test the update 💯💯💯

**Comment by essaund** [comment]
@Rkroy 

It totally looks good. 

Not sure if you still have time. But adding a configurable timer delay (like on pop ups) can be really great for this feature. 

Sorry for this additional request.

**Comment by Rkroy** [comment]
Hi @essaund, we've added an option to setup time for animation, please check.

**Comment by Rkroy** [comment]
Hi @essaund, here is the screenshot.
![photo_2023-08-30_10-26-43](https://github.com/wpquads/quick-adsense-reloaded/assets/43204388/04eed613-387e-4bc4-bf14-eb7fcd0c7838)

**Comment by essaund** [comment]
@Rkroy thanks for doing a wonderful job.

I have tested it and found it almost perfect. 

There's some slight issue with missing CSS properties that are making the sticky ad to display incorrectly. 

I have documented the issue in video and showcased how to fix it. It's a minor issue.

https://drive.google.com/file/d/1Oki37nH6kTiIIF_KyIAsaGWd7o-li9C4/view?usp=sharing

**Comment by essaund** [comment]
Version 2.0.76 breaks sticky ads from working. It was supposed to fix the issues about missing CSS codes but it stops sticky ads from showing. 

I have downgraded back to 2.0.75.

**Comment by essaund** [comment]
@Sanjeevsetu @akshaywali @Rkroy @Sasirekhamarella 

Someone please help. You broke this feature when all it needed was just a slight improvement to the CSS. It no longer works and we're in version 2.0.78 of WPQuads and it's still not working
