### ISSUE TITLE
Sticky ads are not working

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#739]
Sticky ads are not working, but when you roll back the plugin to the previous version, it's working fine.

Ref video: https://monosnap.com/direct/ISnf4Kx1nupP2ghXuIp0Iow4Nq2ZCq 

Ref ticket: https://magazine3.in/conversation/125597?folder_id=29

**Comment by Sasirekhamarella** [comment]
Same: https://wordpress.org/support/topic/sticky-ads-not-work/
