### ISSUE TITLE
PHP Warning on server and Error

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#760]
[Mon May 22 09:27:13.275845 2023] [proxy_fcgi:error] [pid 24476:tid 140668903061248] [client 139.59.6.211:0] AH01071: Got error '/wp-content/plugins/quick-adsense-reloaded/includes/reports/analytics.php on line 2............n line 293PHP message: PHP Warning: in_array() expects parameter 2 to be array, int given in wp-content/plugins/quick-adsense-reloaded/includes/reports/analytics.php on line 293'

**Comment by akshaywali** [comment]
Issue was already fixed in  master
