### ISSUE TITLE
Undefined array key "ad" 

### ISSUE THREAD

**Issue by dausruddin** [wpquads/quick-adsense-reloaded#761]
I'm getting this error since recently

```
2023/05/27 11:07:23 [error] 2282857#2282857: *16871778 FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined array key "ad" in /home/user/html/wp-content/plugins/quick-adsense-reloaded/includes/api.php on line 136;
```

For now I had to disable the plugin since the error came in like bullets in my log file. 

PHP: 8.2.5
AdSense Integration WP QUADS: 1.4.2
AdSense Integration WP QUADS PRO: 2.0.71

**Comment by Sdaud1950** [comment]
Same issue : 
https://magazine3.in/conversation/161933?folder_id=29

**Comment by akshaywali** [comment]
Pushed in update 2.0.73
