### ISSUE TITLE
Debug Error

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#77]
Notice: Undefined index: id in /home/mattk/public_html/garage/wp-content/plugins/quick-adsense-reloaded/includes/admin/settings/display-settings.php on line 116

![image](https://user-images.githubusercontent.com/16532359/77503256-36f4b780-6e83-11ea-8405-d9d56d8e693e.png)

**Comment by jasthilokesh** [comment]
Issue fixed with the update 1.8.17
