### ISSUE TITLE
After paragraph option is not working proprely in AMP

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#780]
Ref ticket:- https://magazine3.in/conversation/164594?folder_id=21

Description
When we select the option after paragraph, it's working perfectly in non-amp, but when we check in amp, ads are not displayed after paragraph; all ads show at the beginning of the paragraph. 

Issue screenshot
https://prnt.sc/KksUv3bwEfqN

**Comment by Sanjeevsetu** [comment]
This ticket is related to https://github.com/wpquads/quick-adsense-reloaded/issues/785. It has been fixed in that.
