### ISSUE TITLE
Carousel Ad width is not working properly

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#804]
On the first publish of the carousel ad the ad width is exceeded.
Reference Screenshot: https://prnt.sc/QVHWPp6TF6_1

If we add small CSS in the customizer the issue will get fixed.
.quads_carousel_img {
    width: 100%;
}

**Comment by Sanjeevsetu** [comment]
Ticket seems to invalid. We are closing this ticket
