### ISSUE TITLE
Global Excluder is not working

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#809]
Settings -> Features -> Global Excluder is not working. Ref: 
[Screencast 2023-09-02 18-17-19.webm](https://github.com/wpquads/quick-adsense-reloaded/assets/11539242/e4cefbc2-8001-45e4-96bc-63fcca1a07e8)

**Comment by Rkroy** [comment]
Fix has been done in Pro.
