### ISSUE TITLE
The manual shortcodes destroy font size

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#81]
With the shortcode attached to the text without a line in between the size is 16 Px compared to the normal text which is 18, on PC you do not notice much but on mobile phones, the lettering looks very very small. 

Reference: https://wordpress.org/support/topic/the-manual-shortcodes-destroy-my-font-size/

For Example——-> https://bit.ly/2RMzzj9
Pics in HTML——->https://ibb.co/d7YRqTG
Normal Pics——-> https://ibb.co/RbzgBM5

**Comment by jasthilokesh** [comment]
Unable to recreate the issue.
