### ISSUE TITLE
Ad rotate shows desktop banner Whereas mobile specific banner is there

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#812]
Step to produce the issues.

1. Add two banner ads with both the banner mobile and desktop. They work fine individually. They show desktop banner for desktop and mobile banner for mobile.

2. Create Rotator and select both the above ads and see the result in desktop and mobile. Always there will be desktop banners

**Comment by Rkroy** [comment]
Fix has been done in Pro.
