### ISSUE TITLE
Plugin is interfering with the amp-ad script

### ISSUE THREAD

**Issue by DikshantJoshi** [wpquads/quick-adsense-reloaded#82]
User has noticed that the plugin is interfering with the amp-ad script. When plugin is active and test the link for validation it shows this – https://paste.pics/88d3567be1f974b68b7f30586ec4a465 and when plugin is deactivated then no error.

reference: 
https://wordpress.org/support/topic/plugin-is-interfering-with-the-amp-ad-script-2/

**Comment by jasthilokesh** [comment]
Unable to recreate the issue.
