### ISSUE TITLE
Warning: foreach() argument must be of type array\|object, int given in

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#820]
( ! ) Warning: foreach() argument must be of type array\|object, int given in D:\WAMP\www\magazine32\wp-content\plugins\wp-quads-pro\includes\template-functions.php on line 601

**Comment by Rkroy** [comment]
https://github.com/wpquads/quick-adsense-reloaded/issues/787

**Comment by Sanjeevsetu** [comment]
This was already fixed
