### ISSUE TITLE
 PHP warning is showing on the user end.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#838]
Notice: Undefined property: stdClass::$success in /home/sites/6a/3/36dbdd141a/public_html/wp-content/plugins/quick-adsense-reloaded/includes/scripts.php on line 909

Ref ticket : https://magazine3.in/conversation/200985?folder_id=29

**Comment by askcode21** [comment]
Another user for the same concern: https://wordpress.org/support/topic/showing-this-error-message-in-error-log-file-please-resolve-it/

**Comment by akshaywali** [comment]
Pushed in version 2.0.80
