### ISSUE TITLE
Version 2.0.76 and Above Breaking Sticky Ads Functionality

### ISSUE THREAD

**Issue by askcode21** [wpquads/quick-adsense-reloaded#842]
User reported that version 2.0.76 and above beaks sticky ads.

Reference ticket: https://wordpress.org/support/topic/do-you-have-pop-up-ads-from-bottom-of-the-page/

Github: https://github.com/wpquads/quick-adsense-reloaded/issues/731

**Comment by essaund** [comment]
Can it be merged with this bug on sticky ads too? 

https://wordpress.org/support/topic/sticky-ad-for-desktop-mobile-bug-needs-improvement/

**Comment by essaund** [comment]
Here's the video as earlier promised. 
https://drive.google.com/file/d/1GPnJ-kr6g9cqmMdTzarWe12Cb60dpuKE/view?usp=share_link

**Comment by essaund** [comment]
Here's the video as earlier promised about **_Sticky ADS not working._**
https://drive.google.com/file/d/1GPnJ-kr6g9cqmMdTzarWe12Cb60dpuKE/view?usp=share_link

Take note that I have found a workaround for **_Desktop/Mobile sticky Ads_** as explained here. But it might need some improvement.
https://wordpress.org/support/topic/sticky-ad-for-desktop-mobile-bug-needs-improvement/#post-17144542

**Comment by essaund** [comment]
@Rkroy ~ You worked on this feature. Please pick it up 🙏🏿🙏🏿🙏🏿

**Comment by Sanjeevsetu** [comment]
Hi @essaund 

Sorry for all delay. Yes we re open this ticket and will fix this issue.

**Comment by essaund** [comment]
> Hi @essaund 
> 
> Sorry for all delay. Yes we add it in our next milestone and will fix it soon.

Thanks so much. This is also a critical issue that needs speedy action. Looks like it has been broken for years of not months. 

https://wordpress.org/support/topic/urgent-google-ad-manager-no-longer-works/

**Comment by askcode21** [comment]
@essaund Hi, Can you please raise the ticket for this issue from the below link https://wpquads.com/support/ so that we can assist you there.

**Comment by essaund** [comment]
> @essaund Hi, Can you please raise the ticket for this issue from the below link https://wpquads.com/support/ so that we can assist you there.

Okay, will do so
