### ISSUE TITLE
The “Unexptected token error” shows in browser console

### ISSUE THREAD

**Issue by askcode21** [wpquads/quick-adsense-reloaded#845]
Google AD Manager (GTM) no longer works. The “Unexpected token error” shows in the browser console.

Reference tickets: https://wordpress.org/support/topic/urgent-google-ad-manager-no-longer-works/  and  https://magazine3.in/conversation/205968?folder_id=23

**Comment by essaund** [comment]
Thanks so much for acknowledging this issue. You can mark it as a critical bug and expedite it. 

It has been broken for years now and probably users thought they were doing something wrong. 😕😕😕
