### ISSUE TITLE
PHP warning is showing on the user end.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#851]
\"PHP message: PHP Warning: Undefined array key \"quadsampstickyInCss\" /public/wp-content/plugins/quick-adsense-reloaded/includes/amp-condition-display.php on line 360\"

Ref ticket : https://magazine3.in/conversation/214445?folder_id=29

**Comment by akshaywali** [comment]
Pushed in version 2.0.80
