### ISSUE TITLE
Warning in debug log

### ISSUE THREAD

**Issue by 77naveenop** [wpquads/quick-adsense-reloaded#852]
Warning: file_get_contents(http://ipinfo.io/38.137.41.71/city): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests in /home/indiabulletin/[punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php](http://punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php) on line 686 Warning: file_get_contents(http://ipinfo.io/38.137.41.71/city): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests in /home/indiabulletin/[punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php](http://punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php) on line 686 Warning: file_get_contents(http://ipinfo.io/38.137.41.71/city): failed to open stream: HTTP request failed! HTTP/1.0 429 Too Many Requests in /home/indiabulletin/[punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php](http://punjabibulletin.in/wp-content/plugins/quick-adsense-reloaded/includes/conditions.php) on line 686

reference user : https://magazine3.in/conversation/214240?folder_id=4

**Comment by Sdaud1950** [comment]
Too many errors are displayed in the query monitor, and the user site is running slowly.

Ref screenshot https://prnt.sc/A91pPjjRN5Wk  

Ref Ticket:https://magazine3.in/conversation/235937?folder_id=29

**Comment by akshaywali** [comment]
These error were due to an API call that has now been fixed.

**Comment by akshaywali** [comment]
pushed in 2.0.81
