### ISSUE TITLE
An error is appearing in the classic interface

### ISSUE THREAD

**Issue by sajandara** [wpquads/quick-adsense-reloaded#853]
An error is appearing in the classic interface

Error: WP QUADS - Can not retrive ad settings from vi API. Error: cURL error 6: Could not resolve host: dashboard-api.vidint.net

Ref screenshot: https://monosnap.com/direct/YFVBGm5GRKaw63rP0F7FOFeUCVy3Om

Ref ticket: https://magazine3.in/conversation/214909?folder_id=27

**Comment by sajandara** [comment]
Another user is facing the same issue: 
https://magazine3.in/conversation/216125?folder_id=27

**Comment by MohammedAkramU7** [comment]
Another user is facing the same issue: https://magazine3.in/conversation/223412?folder_id=21

**Comment by Sdaud1950** [comment]
https://magazine3.in/conversation/224091?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.0.79.1
