### ISSUE TITLE
Warnings:

### ISSUE THREAD

**Issue by Sanjeevsetu** [wpquads/quick-adsense-reloaded#855]
Undefined array key "ad_log" in D:\WAMP\www\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\reports\analyticsV2.php on line 288.

 Undefined variable $get_mob_impr_specific_dates in D:\WAMP\www\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\reports\commonV2.php on line 1222

$get_desk_impr_specific_dates in D:\WAMP\www\magazine3\wp-content\plugins\quick-adsense-reloaded\includes\reports\commonV2.php on line 1223

**Comment by akshaywali** [comment]
Pushed in version 2.0.80
