### ISSUE TITLE
Dual HTML tag was added to the source code.

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#868]
Ref ticket:- https://magazine3.in/conversation/243067?folder_id=21

Description:-
When we added the ads dual tags was added in source code.

Issue screenshot:-
https://prnt.sc/Ux0UjN3vm3uk

**Comment by Sdaud1950** [comment]
Ref Ticket : https://magazine3.in/conversation/244994?folder_id=29

**Comment by akshaywali** [comment]
pushed in 2.0.81

**Comment by akshaywali** [comment]
pushed in version 2.0.86
