### ISSUE TITLE
AdsforWP Migrator

### ISSUE THREAD

**Issue by ahmedkaludi** [wpquads/quick-adsense-reloaded#87]

**Comment by ahmedkaludi** [comment]
- [ ] The functionality is not working https://take.ms/d6qY9W

- [ ] Wrong position: It should be in a separate menu called "Importer" next to Tools - which will have an importer for all the other ads plugin in the future, we will be starting with AdsforWP. https://monosnap.com/file/SIQZtAljPaHpjbVSMniFx1xJcps4BJ

- [ ] Labeling is wrong: it should be "Ads for WP" https://take.ms/fmnwt

- [ ] Wrong plugin name - AMPforWP and AdsforWP are two different plugins, that's a blunder: https://take.ms/8pU1h

- [ ] Ads vs Adds - understand the importance of words: https://take.ms/zCtY2 ( https://dictionary.cambridge.org/dictionary/english/ads | https://dictionary.cambridge.org/dictionary/english/add?q=adds )

- [ ] Success Message incorrect: it should be "Ads have been successfully imported" https://take.ms/aTjIx

- [ ] It should just say: Import -  https://take.ms/IDnCO

**Comment by ahmedkaludi** [comment]
**NOTE**

This ticket is on hold until further notice

**Comment by jasthilokesh** [comment]
https://secure.helpscout.net/conversation/1244960370/146521?folderId=2770545

**Comment by jasthilokesh** [comment]
Fixed with the update 2.0.11
