### ISSUE TITLE
 Report tab is showing blank. 

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#870]
The report tab is showing blank. 

Ref ticket:https://magazine3.in/conversation/249620?folder_id=29

**Comment by akshaywali** [comment]
https://github.com/wpquads/quick-adsense-reloaded/commit/afa0384f85c78f9690ebd34ce8de4fa06aae3a28#diff-50aba783b4ea728aa2219aaeb94cb36b7ae1a0687d28be453fe2e2c93fad6e61

**Comment by akshaywali** [comment]
pushed in 2.0.81
