### ISSUE TITLE
PHP Warning (2.0.81): Undefined array key “position”

### ISSUE THREAD

**Issue by askcode21** [wpquads/quick-adsense-reloaded#874]
One of the user reached out to us with this concern that after updating to the latest version 2.0.81 gave PHP warnings.

Warning: /home/website/public_html/wp-content/plugins/quick-adsense-reloaded/includes/template-functions.php on line 3607

reference ticket: https://wordpress.org/support/topic/php-warning-2-0-81-undefined-array-key-position/

**Comment by akshaywali** [comment]
pushed in WP quads 2.0.82
