### ISSUE TITLE
Conflict issue with 2.0.81 version

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#875]
Ref ticket:- https://magazine3.in/conversation/109304?folder_id=21

Description:-
When we update to the 2.0.81 version position, where will the AD appear? fields are not working.

Issue screenshot:-
https://prnt.sc/FneM1ed2GYTd

**Comment by akshaywali** [comment]
pushed in WP quads 2.0.82
