### ISSUE TITLE
Few improvements of Dahsboard

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [wpquads/quick-adsense-reloaded#876]
- [x] These three tabs should be clickable or next and prev should be sticky, it'll be easy to navigate.
https://prnt.sc/NAhzGwOtqp0B

- [x] Count for the selected ads
https://prnt.sc/kutRrHcsLhWE

- [x] In this filters all ads types are appearing even those that are not added on-site, so I think the list should come from the ads that we have added on site and alphabetical order
https://prnt.sc/SfzKVX--_0Bc

- [x] Search is not working properly with ads name search
https://prnt.sc/TF5PTBSk7ziu

- [x] As we have multiple ads to copy shortcode, we have edit ad and go the last page then we can see the shortcode
Can we add shortcode column
https://prnt.sc/OZwVHN82rQWN

**Comment by akshaywali** [comment]
pushed in version 2.0.86
