### ISSUE TITLE
Mobile Plain Text / HTML / JS	 option is not getting saved

### ISSUE THREAD

**Issue by 77naveenop** [wpquads/quick-adsense-reloaded#879]
When adding any HTML in Mobile Plain Text / HTML / JS option, it strips.

Reference user -: https://wordpress.org/support/topic/mobile-code-strips-html/

**Comment by akshaywali** [comment]
https://github.com/wpquads/quick-adsense-reloaded/commit/7e35b12de877c0fc28542732004a66e23bdaf452

**Comment by akshaywali** [comment]
pushed in WP quads 2.0.82
