### ISSUE TITLE
Ordered ads are not showing in rotation ads in the Auto Rotate type option.

### ISSUE THREAD

**Issue by Sdaud1950** [wpquads/quick-adsense-reloaded#883]
Ordered ads are not showing in rotation ads in the Auto Rotate type option.

Ref ticket : https://magazine3.in/conversation/261713?folder_id=29

**Comment by shridhamdeveloper** [comment]
Refer this commit of pro
https://github.com/wpquads/wp-quads-pro/commit/994d61c77d731d417417559acf7a2dba0e2b0076
