### ISSUE TITLE
Few modification needs to be done in Rotator ads

### ISSUE THREAD

**Issue by 77naveenop** [wpquads/quick-adsense-reloaded#887]
1. Counts & impression will be counted of only that particular which is encountered in frontend.
2. In the Clicks & impression section, data of all the ads should be shown in same box like a hierarchy structure. Here is the reference screenshot https://prnt.sc/jpvpFlPjGEBA
3. Different no. of clicks & impression showing when testing, please refer the screenshots,                                                                           out of reports box -: https://prnt.sc/bkRzyh2MUhb2,
 inside the reports box -: https://prnt.sc/aTVQMqcECDDQ
4. UI design should be improved. 
    a. https://prnt.sc/jpvpFlPjGEBA
    b.https://prnt.sc/NG7Ixyrd_M7w
    c. https://take.ms/5RsEmJ

Reference user -: https://magazine3.in/conversation/261713?folder_id=3

**Comment by shridhamdeveloper** [comment]
Changes in pro plugin
https://github.com/wpquads/wp-quads-pro/commit/b6a7fcef75c7f0e76cdcf1776ef5832387f5fb02
