### ISSUE TITLE
Need to make a compatiblity with Jannah news theme.

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#890]
Ref ticket: https://magazine3.in/conversation/109304?folder_id=21

Description:-
When we tried to add the ads to page that created with the help of Jannah news theme, it wasn't visible in page section.

Here is the screenshot:-
https://prnt.sc/fzcgFGOSOApE

**Comment by akshaywali** [comment]
pushed in version 2.0.86
