### ISSUE TITLE
Ads was not working with official AMP

### ISSUE THREAD

**Issue by MohammedAkramU7** [wpquads/quick-adsense-reloaded#904]
Ref ticket:- https://magazine3.in/conversation/312685?folder_id=21

Description:
When a user creates an ad using our WP Guards plugin and enables the AMP compatibility option, the ads do not appear in the AMP version.

**Comment by akshaywali** [comment]
User is using some ad script to show ads , since amp doesn't support any js script nothing is being shown.

**Comment by akshaywali** [comment]
We have asked user which ad service he intend to  use so that  we can check  feasibility  of that  in amp. Since user  is not responding so closing this ticket for now .
